// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaylist(arg1) {
  return window['go']['app']['App']['AddPlaylist'](arg1);
}

export function AddPlaylistTrack(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddPlaylistTrack'](arg1, arg2, arg3);
}

export function AddSmartPlaylist(arg1, arg2) {
  return window['go']['app']['App']['AddSmartPlaylist'](arg1, arg2);
}

export function AddTrackToQueue(arg1, arg2) {
  return window['go']['app']['App']['AddTrackToQueue'](arg1, arg2);
}

export function ConnectDevice(arg1) {
  return window['go']['app']['App']['ConnectDevice'](arg1);
}

export function CountAlbums() {
  return window['go']['app']['App']['CountAlbums']();
}

export function CountArtists() {
  return window['go']['app']['App']['CountArtists']();
}

export function CountLikedTracks() {
  return window['go']['app']['App']['CountLikedTracks']();
}

export function CountPlaylistTracks(arg1) {
  return window['go']['app']['App']['CountPlaylistTracks'](arg1);
}

export function CountPlaylists() {
  return window['go']['app']['App']['CountPlaylists']();
}

export function CountTracks() {
  return window['go']['app']['App']['CountTracks']();
}

export function CreateAPIToken(arg1) {
  return window['go']['app']['App']['CreateAPIToken'](arg1);
}

export function CreateArtist(arg1) {
  return window['go']['app']['App']['CreateArtist'](arg1);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeletePlaylist(arg1) {
  return window['go']['app']['App']['DeletePlaylist'](arg1);
}

export function DeletePlaylistTrack(arg1) {
  return window['go']['app']['App']['DeletePlaylistTrack'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['app']['App']['DeleteUser'](arg1);
}

export function DeleteUserToken(arg1) {
  return window['go']['app']['App']['DeleteUserToken'](arg1);
}

export function DisconnectDevice() {
  return window['go']['app']['App']['DisconnectDevice']();
}

export function FilterTracks(arg1, arg2, arg3) {
  return window['go']['app']['App']['FilterTracks'](arg1, arg2, arg3);
}

export function GetAlbum(arg1) {
  return window['go']['app']['App']['GetAlbum'](arg1);
}

export function GetArtist(arg1) {
  return window['go']['app']['App']['GetArtist'](arg1);
}

export function GetArtistTopTracks(arg1) {
  return window['go']['app']['App']['GetArtistTopTracks'](arg1);
}

export function GetCachedUsers() {
  return window['go']['app']['App']['GetCachedUsers']();
}

export function GetConnectedDeviceID() {
  return window['go']['app']['App']['GetConnectedDeviceID']();
}

export function GetPlayerState() {
  return window['go']['app']['App']['GetPlayerState']();
}

export function GetPlaylist(arg1) {
  return window['go']['app']['App']['GetPlaylist'](arg1);
}

export function GetUser() {
  return window['go']['app']['App']['GetUser']();
}

export function ImportAlbum(arg1) {
  return window['go']['app']['App']['ImportAlbum'](arg1);
}

export function LikeTrack(arg1) {
  return window['go']['app']['App']['LikeTrack'](arg1);
}

export function ListAlbums() {
  return window['go']['app']['App']['ListAlbums']();
}

export function ListAlbumsByArtist(arg1) {
  return window['go']['app']['App']['ListAlbumsByArtist'](arg1);
}

export function ListArtists() {
  return window['go']['app']['App']['ListArtists']();
}

export function ListDevices() {
  return window['go']['app']['App']['ListDevices']();
}

export function ListEntityEvents() {
  return window['go']['app']['App']['ListEntityEvents']();
}

export function ListFeaturedAlbumsByArtist(arg1) {
  return window['go']['app']['App']['ListFeaturedAlbumsByArtist'](arg1);
}

export function ListImportItems(arg1, arg2) {
  return window['go']['app']['App']['ListImportItems'](arg1, arg2);
}

export function ListLikedTracks() {
  return window['go']['app']['App']['ListLikedTracks']();
}

export function ListPlaylistTracks(arg1) {
  return window['go']['app']['App']['ListPlaylistTracks'](arg1);
}

export function ListPlaylists() {
  return window['go']['app']['App']['ListPlaylists']();
}

export function ListTracksByAlbum(arg1) {
  return window['go']['app']['App']['ListTracksByAlbum'](arg1);
}

export function ListUserRoles() {
  return window['go']['app']['App']['ListUserRoles']();
}

export function ListUserTokens() {
  return window['go']['app']['App']['ListUserTokens']();
}

export function ListUsers(arg1) {
  return window['go']['app']['App']['ListUsers'](arg1);
}

export function LoginServerUser(arg1, arg2, arg3) {
  return window['go']['app']['App']['LoginServerUser'](arg1, arg2, arg3);
}

export function LogoutLocalUser() {
  return window['go']['app']['App']['LogoutLocalUser']();
}

export function NextRepeat() {
  return window['go']['app']['App']['NextRepeat']();
}

export function NextTrack() {
  return window['go']['app']['App']['NextTrack']();
}

export function PlayPause() {
  return window['go']['app']['App']['PlayPause']();
}

export function PreviousTrack() {
  return window['go']['app']['App']['PreviousTrack']();
}

export function RateTrack(arg1, arg2) {
  return window['go']['app']['App']['RateTrack'](arg1, arg2);
}

export function RemoveDevice(arg1) {
  return window['go']['app']['App']['RemoveDevice'](arg1);
}

export function RemoveDeviceAndToken(arg1) {
  return window['go']['app']['App']['RemoveDeviceAndToken'](arg1);
}

export function RemoveDeviceToken(arg1) {
  return window['go']['app']['App']['RemoveDeviceToken'](arg1);
}

export function SearchFull(arg1) {
  return window['go']['app']['App']['SearchFull'](arg1);
}

export function SearchMusicBrainz(arg1, arg2) {
  return window['go']['app']['App']['SearchMusicBrainz'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function SendMessage3(arg1) {
  return window['go']['app']['App']['SendMessage3'](arg1);
}

export function SendMessage4(arg1) {
  return window['go']['app']['App']['SendMessage4'](arg1);
}

export function ServerOnline() {
  return window['go']['app']['App']['ServerOnline']();
}

export function ServerStatus() {
  return window['go']['app']['App']['ServerStatus']();
}

export function Start(arg1, arg2, arg3) {
  return window['go']['app']['App']['Start'](arg1, arg2, arg3);
}

export function SupportsSync() {
  return window['go']['app']['App']['SupportsSync']();
}

export function SyncLibrary() {
  return window['go']['app']['App']['SyncLibrary']();
}

export function Themes() {
  return window['go']['app']['App']['Themes']();
}

export function ToggleShuffle() {
  return window['go']['app']['App']['ToggleShuffle']();
}

export function UnlikeTrack(arg1) {
  return window['go']['app']['App']['UnlikeTrack'](arg1);
}

export function UpdateAlbum(arg1, arg2) {
  return window['go']['app']['App']['UpdateAlbum'](arg1, arg2);
}

export function UpdateArtist(arg1, arg2) {
  return window['go']['app']['App']['UpdateArtist'](arg1, arg2);
}

export function UpdatePlaylist(arg1, arg2) {
  return window['go']['app']['App']['UpdatePlaylist'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTrack(arg1, arg2) {
  return window['go']['app']['App']['UpdateTrack'](arg1, arg2);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateUser'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadAlbumImage(arg1, arg2) {
  return window['go']['app']['App']['UploadAlbumImage'](arg1, arg2);
}

export function UploadArtistImage(arg1, arg2) {
  return window['go']['app']['App']['UploadArtistImage'](arg1, arg2);
}

export function UploadPlaylistImage(arg1, arg2) {
  return window['go']['app']['App']['UploadPlaylistImage'](arg1, arg2);
}

export function UploadUserImage() {
  return window['go']['app']['App']['UploadUserImage']();
}
