// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {uuid} from '../models';
import {serverclient} from '../models';

export function AddPlaylist(arg1:types.Playlist):Promise<void>;

export function AddPlaylistTrack(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddSmartPlaylist(arg1:types.PlaylistBase,arg2:types.TrackFilter):Promise<void>;

export function AddTrackToQueue(arg1:string,arg2:string):Promise<void>;

export function ConnectDevice(arg1:string):Promise<void>;

export function CountAlbums():Promise<number>;

export function CountArtists():Promise<number>;

export function CountLikedTracks():Promise<number>;

export function CountPlaylistTracks(arg1:string):Promise<number>;

export function CountPlaylists():Promise<number>;

export function CountTracks():Promise<number>;

export function CreateAPIToken(arg1:string):Promise<string>;

export function CreateArtist(arg1:types.ArtistBase):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DeletePlaylistTrack(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function DeleteUserToken(arg1:string):Promise<void>;

export function DisconnectDevice():Promise<void>;

export function FilterTracks(arg1:types.TrackFilter,arg2:number,arg3:number):Promise<types.ListPaginationPayload_github_com_bragemusic_core_pkg_types_TrackDetailed_>;

export function GetAlbum(arg1:string):Promise<types.AlbumDetailed>;

export function GetArtist(arg1:string):Promise<types.Artist>;

export function GetArtistTopTracks(arg1:string):Promise<Array<types.TrackDetailed>>;

export function GetCachedUsers():Promise<Array<types.UserDetails>>;

export function GetConnectedDeviceID():Promise<any>;

export function GetPlayerState():Promise<types.PlayerState>;

export function GetPlaylist(arg1:string):Promise<types.Playlist>;

export function GetUser():Promise<types.UserDetails>;

export function ImportAlbum(arg1:any):Promise<void>;

export function LikeTrack(arg1:string):Promise<void>;

export function ListAlbums():Promise<Array<types.AlbumDetailed>>;

export function ListAlbumsByArtist(arg1:string):Promise<Array<types.AlbumDetailed>>;

export function ListArtists():Promise<Array<types.ArtistDetailed>>;

export function ListDevices():Promise<Array<types.DeviceDetailed>>;

export function ListEntityEvents():Promise<Array<types.EntityEvent>>;

export function ListFeaturedAlbumsByArtist(arg1:string):Promise<Array<types.AlbumDetailed>>;

export function ListImportItems(arg1:number,arg2:number):Promise<types.ListPaginationPayload_github_com_bragemusic_core_pkg_types_Import_>;

export function ListLikedTracks():Promise<Array<types.TrackDetailed>>;

export function ListPlaylistTracks(arg1:string):Promise<Array<types.TrackDetailed>>;

export function ListPlaylists():Promise<Array<types.Playlist>>;

export function ListTracksByAlbum(arg1:string):Promise<Array<types.TrackDetailed>>;

export function ListUserRoles():Promise<Array<types.UserRole>>;

export function ListUserTokens():Promise<Array<types.TokenLimited>>;

export function ListUsers(arg1:boolean):Promise<Array<types.UserDetails>>;

export function LoginServerUser(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function LogoutLocalUser():Promise<void>;

export function NextRepeat():Promise<void>;

export function NextTrack():Promise<void>;

export function PlayPause():Promise<void>;

export function PreviousTrack():Promise<void>;

export function RateTrack(arg1:string,arg2:number):Promise<void>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RemoveDeviceAndToken(arg1:string):Promise<void>;

export function RemoveDeviceToken(arg1:string):Promise<void>;

export function SearchFull(arg1:string):Promise<Array<types.SearchItem>>;

export function SearchMusicBrainz(arg1:string,arg2:string):Promise<types.ListPayload_github_com_bragemusic_core_pkg_musicbrainz_SearchResults_>;

export function SendMessage(arg1:string):Promise<void>;

export function SendMessage3(arg1:boolean):Promise<void>;

export function SendMessage4(arg1:number):Promise<void>;

export function ServerOnline():Promise<boolean>;

export function ServerStatus():Promise<types.ServerApiInfo>;

export function Start(arg1:types.PlayContextType,arg2:string,arg3:number):Promise<void>;

export function SupportsSync():Promise<boolean>;

export function SyncLibrary():Promise<void>;

export function Themes():Promise<Array<types.ThemeDescription>>;

export function ToggleShuffle():Promise<void>;

export function UnlikeTrack(arg1:string):Promise<void>;

export function UpdateAlbum(arg1:string,arg2:types.AlbumUpdate):Promise<void>;

export function UpdateArtist(arg1:uuid.UUID,arg2:types.Artist):Promise<void>;

export function UpdatePlaylist(arg1:string,arg2:types.Playlist):Promise<void>;

export function UpdateProfile(arg1:any,arg2:any,arg3:any,arg4:any,arg5:any):Promise<void>;

export function UpdateTrack(arg1:string,arg2:types.TrackUpdate):Promise<void>;

export function UpdateUser(arg1:string,arg2:string,arg3:string,arg4:any,arg5:Array<string>):Promise<void>;

export function UploadAlbumImage(arg1:string,arg2:serverclient.FileUpload):Promise<void>;

export function UploadArtistImage(arg1:string,arg2:serverclient.FileUpload):Promise<void>;

export function UploadPlaylistImage(arg1:string,arg2:serverclient.FileUpload):Promise<void>;

export function UploadUserImage():Promise<void>;
